{"name":"getUserListAPITest","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [200] but found [404]","trace":"java.lang.AssertionError: expected [200] but found [404]\n\tat org.testng.Assert.fail(Assert.java:93)\n\tat org.testng.Assert.failNotEquals(Assert.java:512)\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:134)\n\tat org.testng.Assert.assertEquals(Assert.java:115)\n\tat org.testng.Assert.assertEquals(Assert.java:388)\n\tat org.testng.Assert.assertEquals(Assert.java:398)\n\tat com.qa.gorest.tests.GetUserAPITest.getUserListAPITest(GetUserAPITest.java:33)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:661)\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:744)\n\tat org.testng.TestRunner.run(TestRunner.java:602)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:380)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:289)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1226)\n\tat org.testng.TestNG.runSuites(TestNG.java:1144)\n\tat org.testng.TestNG.run(TestNG.java:1115)\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)\n"},"stage":"finished","description":"test case name: verify get user api with existing user...","steps":[],"attachments":[{"name":"getUserListAPITest failed and screenshot taken!","source":"442b5788-a844-4239-a3e1-1e2be479464f-attachment","type":"text/plain"}],"parameters":[],"start":1573795569590,"stop":1573795572688,"uuid":"74c108c2-4cfe-46ea-bce0-0b701d89de78","historyId":"624cc9696680ffd1335e6140f776a87b","fullName":"com.qa.gorest.tests.GetUserAPITest.getUserListAPITest","labels":[{"name":"package","value":"com.qa.gorest.tests.GetUserAPITest"},{"name":"testClass","value":"com.qa.gorest.tests.GetUserAPITest"},{"name":"testMethod","value":"getUserListAPITest"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"com.qa.gorest.tests.GetUserAPITest"},{"name":"host","value":"Bobs-MBP.fios-router.home"},{"name":"thread","value":"18761@Bobs-MBP.fios-router.home.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"severity","value":"critical"}],"links":[]}